export const extras = [
  {
    id: 'changing_bed_sheets',
    name: 'changing_bed_sheets',
    extra: 'Changing Bed Sheets',
    price: '$5 per bed',
    checked: false,
  },
  {
    id: 'wash_and_dry_laundry',
    name: 'wash_and_dry_laundry',
    extra: 'Wash & Dry Laundry',
    price: '$10 per load',
    checked: false,
  },
  {
    id: 'dusting_blinds',
    name: 'dusting_blinds',
    extra: 'Dusting & Cleaning Blinds',
    price: '$20 flat for all blinds',
    checked: false,
  },
  {
    id: 'interior_window_cleaning',
    name: 'interior_window_cleaning',
    extra: 'Interior Window Cleaning',
    price: '$4 per window',
    checked: false,
  },
  {
    id: 'exterior_window_cleaning',
    name: 'exterior_window_cleaning',
    extra: 'Exterior Window Cleaning',
    price: '$6 per window',
    checked: false,
  },
  {
    id: 'cabinets',
    name: 'cabinets',
    extra: 'Cleaning Interior of Cabinets',
    price: '$35 flat per the entire shelf',
    checked: false,
  },
  {
    id: 'fridge',
    name: 'fridge',
    extra: 'Fridge Cleaning',
    price: '$25 flat',
    checked: false,
  },
  {
    id: 'oven',
    name: 'oven',
    extra: 'Oven Cleaning',
    price: '$35 flat',
    checked: false,
  },
  {
    id: 'cabinet_organization',
    name: 'cabinet_organization',
    extra: 'Cabinet Organization',
    price: '$50 flat',
    checked: false,
  },
]
