export const extras = [
  {
    id: 'changing_bed_sheets',
    key: 'changingBedSheets',
    name: 'changing_bed_sheets',
    extra: 'Changing Bed Sheets',
    price: 5,
    perUnit: true,
    flat: false,
    perLoad: false,
    checked: false,
  },
  {
    id: 'wash_and_dry_laundry',
    key: 'washAndDryLaundry',
    name: 'wash_and_dry_laundry',
    extra: 'Wash & Dry Laundry',
    price: 10,
    perUnit: false,
    flat: false,
    perLoad: true,
    checked: false,
  },
  {
    id: 'dusting_blinds',
    key: 'dustingAndCleaningBlinds',
    name: 'dusting_blinds',
    extra: 'Dusting & Cleaning Blinds',
    price: 20,
    perUnit: true,
    flat: false,
    perLoad: false,
    checked: false,
  },
  {
    id: 'interior_window_cleaning',
    key: 'interiorWindowCleaning',
    name: 'interior_window_cleaning',
    extra: 'Interior Window Cleaning',
    price: 4,
    perUnit: true,
    flat: false,
    perLoad: false,
    checked: false,
  },
  {
    id: 'exterior_window_cleaning',
    key: 'exteriorWindowCleaning',
    name: 'exterior_window_cleaning',
    extra: 'Exterior Window Cleaning',
    price: 6,
    perUnit: true,
    flat: false,
    perLoad: false,
    checked: false,
  },
  {
    id: 'cabinets',
    key: 'cleaningInteriorOfCabinets',
    name: 'cabinets',
    extra: 'Cleaning Interior of Cabinets',
    price: 35,
    perUnit: false,
    flat: true,
    perLoad: false,
    checked: false,
  },
  {
    id: 'fridge',
    key: 'fridgeCleaning',
    name: 'fridge',
    extra: 'Fridge Cleaning',
    price: 25,
    perUnit: false,
    flat: true,
    perLoad: false,
    checked: false,
  },
  {
    id: 'oven',
    key: 'ovenCleaning',
    name: 'oven',
    extra: 'Oven Cleaning',
    price: 35,
    perUnit: false,
    flat: true,
    perLoad: false,
    checked: false,
  },
  {
    id: 'cabinet_organization',
    key: 'cabinetOrganization',
    name: 'cabinet_organization',
    extra: 'Cabinet Organization',
    price: 50,
    perUnit: false,
    flat: true,
    perLoad: false,
    checked: false,
  },
]
