export const serviceFrequency = [
  {
    id: 1,
    title: 'Just once',
    key: 'justOnce',
    circleIconColor: 'h-5 w-5 text-slate-600',
    borderColor: 'border-slate-500',
    active: 'border-slate-500 ring-2 ring-slate-500',
    textColor: 'relative block text-sm font-medium text-slate-800',
    discount: 0.0,
    selected: false,
  },
  {
    id: 2,
    title: 'Every week',
    key: 'everyWeek',
    savingsTip: 'Get 20% off',
    color:
      'inline-flex whitespace-nowrap rounded-full bg-cyan-500 px-4 py-1 text-xs font-semibold text-white shadow shadow-cyan-500/75',
    circleIconColor: 'h-5 w-5 text-cyan-600',
    borderColor: 'border-cyan-500',
    active: 'border-cyan-500 ring-2 ring-cyan-500',
    textColor: 'relative block text-sm font-medium text-cyan-800',
    discount: 0.2,
    selected: false,
  },
  {
    id: 3,
    title: 'Every 2 weeks',
    key: 'every2Weeks',
    savingsTip: 'Get 15% off',
    color:
      'inline-flex whitespace-nowrap rounded-full bg-green-500 px-4 py-1 text-xs font-semibold text-white shadow shadow-green-500/75',
    circleIconColor: 'h-5 w-5 text-green-600',
    borderColor: 'border-green-500',
    active: 'border-green-500 ring-2 ring-green-500',
    textColor: 'relative block text-sm font-medium text-green-800',
    discount: 0.15,
    selected: false,
  },
  {
    id: 4,
    title: 'Once a month',
    key: 'onceAMonth',
    savingsTip: 'Get 10% off',
    color:
      'inline-flex whitespace-nowrap rounded-full bg-indigo-500 px-4 py-1 text-xs font-semibold text-white shadow shadow-indigo-500/75',
    circleIconColor: 'h-5 w-5 text-indigo-600',
    borderColor: 'border-indigo-500',
    active: 'border-indigo-500 ring-2 ring-indigo-500',
    textColor: 'relative block text-sm font-medium text-indigo-800',
    discount: 0.1,
    selected: false,
  },
]
